module.exports = {
  chain: [
    {
      type: 'autogenerated',
      dirName: 'chain',
    },
  ],
  sdk: [
    'sdk/introduction',
    {
      'Workshop': [
        {
          type: 'autogenerated',
          dirName: 'sdk/0-workshop',
        },
      ],
    },
    {
      'Core KILT Features': [
        {
          type: 'autogenerated',
          dirName: 'sdk/1-core-feature',
        },
      ],
    },
    {
      'SDK Reference': [
        {
          type: 'autogenerated',
          dirName: 'sdk/2-reference',
        },
      ],
    },
  ],
}
