module.exports = {
  chain: [
    {
      type: 'autogenerated',
      dirName: 'develop/02_chain',
    },
  ],
  workshop: [{ type: 'autogenerated', dirName: 'develop/01_sdk/02_tutorial' }],
  dApp: [{ type: 'autogenerated', dirName: 'develop/07_dApp' }],
  opendid: [{ type: 'autogenerated', dirName: 'develop/08_opendid'}],

  sdk: [
    { type: 'autogenerated', dirName: 'develop/01_sdk' },
    {
      type: 'link',
      label: 'API Documentation',
      href: 'https://kiltprotocol.github.io/sdk-js/index.html',
    },
  ],
}
