{
 "title": "spiritnet",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  { "title": "Blockchain metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Proposer Block Construction Time",
   "type": "timeseries",
   "description": "histogram 90th quantiles for time to construct a block (seconds) More info: https://prometheus.io/docs/prometheus/latest/querying/functions/#histogram_quantile",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum(rate(substrate_proposer_block_constructed_bucket[5m])) by (le))",
     "legendFormat": "Histogram"
    }
   ]
  },
  {
   "title": "Blocktime",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "($__to - $__from) / (quantile(0.8,increase(substrate_block_height{status=\"best\"}[$__range])) * 1000)"
    }
   ]
  },
  {
   "title": "Finalized Blocks per Min",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(substrate_block_height{status=\"finalized\"}[10m])*60",
     "legendFormat": "{{app}}"
    },
    {
     "expr": "quantile(0.8,rate(substrate_block_height{status=\"finalized\"}[60m])*60)",
     "legendFormat": "60min 0.9 quantile"
    },
    { "expr": "5" }
   ]
  },
  {
   "title": "RPC Calls",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(substrate_rpc_calls_total[5m])",
     "legendFormat": "{{statefulset_kubernetes_io_pod_name}}"
    }
   ]
  },
  {
   "title": "Finalized Block Height",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "max(substrate_block_height{status=\"finalized\"}) by (app)",
     "legendFormat": "{{app}}"
    }
   ]
  },
  {
   "title": "Peer Count",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max(substrate_sub_libp2p_peers_count) by (app)",
     "legendFormat": "{{app}}"
    }
   ]
  },
  {
   "title": "Storage Subscriber",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max(substrate_storage_notification_subscribers{action=\"added\"} - ignoring(action) substrate_storage_notification_subscribers{action=\"removed\"}) by (statefulset_kubernetes_io_pod_name)",
     "legendFormat": "{{statefulset_kubernetes_io_pod_name}}"
    }
   ]
  },
  {
   "title": "Best Block Height",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "max(substrate_block_height{status=\"best\"}) by (app)",
     "legendFormat": "{{app}}"
    }
   ]
  },
  {
   "title": "Transactions (Ready)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "substrate_ready_transactions_number",
     "legendFormat": "{{app}}"
    }
   ]
  },
  { "title": "Parachain Node Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  {
   "title": "Parachain Blocktime",
   "type": "stat",
   "description": "Average blocktime over a 10min window",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min(1/rate(substrate_block_height{status=\"finalized\"}[10m])) by (app)",
     "legendFormat": "{{app}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 8, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{container_name!=\"POD\",container_name!=\"\",image=~\"348099934012.dkr.ecr.eu-central-1.amazonaws.com/kilt-parachain/collator.*\"}) by (pod_name)",
     "legendFormat": "{{pod_name}}"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 8, "x": 8, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{name=~\"^k8s_.*\",container_name!=\"POD\",namespace=\"spiritnet\",image=~\"348099934012.dkr.ecr.eu-central-1.amazonaws.com/kilt-parachain/collator.*\"}[2m])) by (pod_name, container_name)",
     "legendFormat": "{{pod_name}}"
    }
   ]
  },
  { "title": "Available Storage", "type": "timeseries", "gridPos": { "h": 12, "w": 8, "x": 16, "y": 34 }, "fieldConfig": { "defaults": { "unit": "bytes" } } },
  {
   "title": "Relay Peer Count",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max(polkadot_sub_libp2p_peers_count) by (app)",
     "legendFormat": "{{app}}"
    }
   ]
  },
  {
   "title": "Finalized Block Height",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "max(polkadot_block_height{status=\"finalized\"}) by (app)",
     "legendFormat": "{{app}}"
    }
   ]
  }
 ]
}